### ISSUE TITLE
Sound Transit 40_gtfs.zip Incomplete and Routes Dispersed

### ISSUE THREAD

**Issue by RideSchedules** [SoundTransit/soundtransit-rds#17]
Hello,

The Sound Transit (40_gtfs.zip) is not a complete data set with all routes.  Some routes are dispersed in other files (3_gtfs.zip).

I was able to publish all static GTFS files and activate OneBusAway on rideschedules.com where supported except for Sound Transit. 

If a link to a complete dataset with OBA compatible files becomes available, I can activate OneBusAway on rideschedules.com.

**Comment by michaelberman** [comment]
Hi, I'm not sure I fully understand the question that you're asking. Because Sound Transit doesn't actually operate our bus service (it's operated by King County Metro, Community Transit, or Pierce Transit, depending on where the service originates), we also don't do our own scheduling. 

Can you please provide more detail on what you're looking for, and we'll try to figure out what to do.

Thanks!

**Comment by RideSchedules** [comment]
I'm looking for a URL link to a complete GTFS file for Sound Transit that uses the OneBusAway compatible identifiers.
