### ISSUE TITLE
All RSS Links Broken

### ISSUE THREAD

**Issue by RideSchedules** [SoundTransit/soundtransit-rds#39]
All the RSS links for Alerts are 404.

For example:

http://www.soundtransit.org/Developer-resources/schedules/alerts.xml?rssFeed=true

**Comment by soundtransitdev** [comment]
This is an open issue, however technically it’s unrelated to open transit data so I’m going to go ahead and close it.  These alerts are part of Sound Transit’s Communications division and not part of the gtfs data set as yet. They are currently unavailable due to a backend infrastructure  change.  I anticipate that the RSS feeds will be back up soon'ish. If anyone needs to follow up with me directly for status please do and reference #860

Thanks,
Juliet


Juliet Chase
Sr. IT Systems Analyst
Sound Transit
Juliet.chase@soundtransit.org

From: "rideschedules.com"
Reply-To: SoundTransit/soundtransit-rds
Date: Tuesday, July 21, 2015 at 5:31 PM
To: SoundTransit/soundtransit-rds
Subject: [soundtransit-rds] All RSS Links Broken (#39)


All the RSS links for Alerts are 404.

For example:

http://www.soundtransit.org/Developer-resources/schedules/alerts.xml?rssFeed=true

**Comment by bbodenmiller** [comment]
When do you think we might be able to get bus and transit status data via something like GTFS-RT? E.g. Some way to know when buses are broke down, blocked, stops closed, etc.?
