### ISSUE TITLE
Major delays result in no realtime data or alerts

### ISSUE THREAD

**Issue by bbodenmiller** [SoundTransit/soundtransit-rds#47]
Buses are seeing 45+ minute delays tonight and for the most part no realtime data is being published. Or alerts that realtime is failing and delays occurring due to protests, etc.

There are thousands of technology professionals in this region and many of us would love to help if you'd get us all together and be willing to let us help implement some solutions.

**Comment by soundtransitdev** [comment]
Hi Ben,

I feel you’re pain and I can honestly say that everyone I’ve worked with across the region’s agencies is committed to improving the rider experience.  That said, government agencies have lots of rules to follow which tends to slow things down and when multiple agencies intersect, well….  There are also lots of competing priorities – is real-time more or less important than having enough busses, etc.? - the answer largely depends on why you’re still standing at the bus stop instead of in a seat.  I think it’s unlikely that there will be a hackathon direct into Metro’s systems or OBA but that doesn’t mean there can’t be one for better communication from riders to government or rider to rider. OBA is currently working to improve the feedback process in the app which in turn may yield system improvements if the communication of problems is more streamlined because the true magnitude will likely become more apparent to the decision makers. What I’m getting at is if you have ideas or if there is enough impetus for a crowd source event that a) doesn’t require government funds or extensive use of personnel and b) coalesces regional communication instead of further diluting it then I think you might find that there is more support for change than you’re feeling when standing out in the rain waiting for the bus :-)

Regards,
Juliet
