### ISSUE TITLE
Some timestamps are in milliseconds, not seconds. 

### ISSUE THREAD

**Issue by gcamp** [SoundTransit/soundtransit-rds#48]
From a GTFS-rt for we just got now, the timestamps for the stop_time_update -> departure is in milliseconds, it should be in seconds.

```json 
header {
  gtfs_realtime_version: "1.0"
  timestamp: 1447793107
}
entity {
  id: "1"
  trip_update {
    trip {
      trip_id: "28851037"
      route_id: "100162"
    }
    stop_time_update {
      arrival {
      }
      departure {
        time: 1447792969000
      }
      stop_id: "25752"
    }
    vehicle {
      id: "7222"
    }
    timestamp: 1447792952
    delay: 171
  }
}
```

**Comment by bbodenmiller** [comment]
@bdferris do you know if this is why Google Maps isn't showing real-time anymore?

**Comment by gcamp** [comment]
@bbodenmiller We fixed it in Transit App server side, so real time should be back now.

**Comment by JulietChase** [comment]
This issue is being addressed by Sound Transit on the core data but as it requires code modification it has to go through our change management process. So I can't offer a specific deployment date but it should be resolved in the next two weeks.  And yes, Google Maps has turned off real-time due to this issue.

**Comment by JulietChase** [comment]
Closing as this issue has been resolved sufficient for Google maps etc to come back online. Fix in place is bandaid with more permanent solution coming but that transfer should be transparent to consumers.
